services:
  {{{ \\#://../../../examples/backend.sec-signal-api.yml }}}

  nginx:
    image: nginx:latest
    container_name: secured-signal-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Load SSL certificates: cert.key, cert.crt
      - ./certs:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - secured-signal
    restart: unless-stopped
    networks:
      proxy:
      backend:
        ipv4_address: 172.20.0.100

networks:
  backend:
  proxy:
