notify:
  - name: signal
    platform: signal_messenger
    url: "http://sec-signal-api:8880/auth=API_TOKEN"
    number: "+123400001"
    recipients:
      - "+123400002" # tip: use a placeholder instead
